### ISSUE TITLE
Granting OAuth access has no effect in Firefox.

### ISSUE THREAD

**Issue by phyllisstein** [putdotio/putio-webextension#2]
After installing the extension in Firefox, a window pops up asking me to grant it access to my put.io account. However, clicking "Confirm" has no effect. I don't see any errors logged to the console, either on load or on click---otherwise, I'm just about clueless. Happy to furnish more troubleshooting information if I can; thanks in advance for taking a look.

**Comment by cenkalti** [comment]
Hello @phyllisstein,

The extension does not give any feedback when "confirm" button is clicked. After confirmation, you can use the extension by right-clicking magnet links and select "Download magnet link with put.io" option.

**Comment by phyllisstein** [comment]
🤦‍♂ Gotcha, thanks for clarifying. Should'a tried it out before whingeing.
